# Generated by Django 5.2.7 on 2025-10-23 19:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='data',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='valor',
        ),
        migrations.AddField(
            model_name='transacao',
            name='categoriadeop',
            field=models.CharField(choices=[('Contribuição', 'Contribuição'), ('Empréstimo', 'Empréstimo'), ('Kixikila', 'Kixikila'), ('Oferta', 'Oferta'), ('Compra', 'Compra'), ('Salário', 'Salário')], default='Contribuição', max_length=50),
        ),
        migrations.AddField(
            model_name='transacao',
            name='datadatransacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transacao',
            name='estado',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='transacao',
            name='idbeneficiario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_recebidas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacao',
            name='idordenante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_feitas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacao',
            name='idtransacao',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='transacao',
            name='notasdatransacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='pin',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='transacao',
            name='prazodatransacao',
            field=models.CharField(default='Sem Data', max_length=50),
        ),
        migrations.AddField(
            model_name='transacao',
            name='tipodeop',
            field=models.CharField(choices=[('Pronto Pagamento', 'Pronto Pagamento'), ('Transação de Crédito', 'Transação de Crédito')], default='Pronto Pagamento', max_length=50),
        ),
        migrations.AddField(
            model_name='transacao',
            name='valoracreditar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
