# Generated by Django 5.2.7 on 2025-10-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0002_remove_transacao_data_remove_transacao_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='tipodeop',
            field=models.CharField(choices=[('Pronto Pagamento', 'Pronto Pagamento'), ('Transação de Crédito', 'Transação de Crédito')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valoracreditar',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
